services:
        spidermonkeydb:
                build: .
                ports:
                        - 4444:4444
                cap_add:
                        - SYS_PTRACE
                security_opt:
                        - seccomp:unconfined
